name: Build and Test
on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin
      - name: Test
        run: mvn  test
      - name: Package
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin

      - name: Package
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_SECRET_USERNAME }}
          password: ${{ secrets.MY_SECRET_PASSWORD }}

      -   name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: prashudocker01/githubcicd:1.4.0